version: '3.2'

services:
  hm:
    build: .
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG=0
    secrets:
      - TOKEN
volumes:
  data:

secrets:
  TOKEN:
    file: ./TOKEN.txt